### ISSUE TITLE
add array questions

### ISSUE THREAD

**Issue by saujibua** [saujibua/Data-Structures-and-Algorithms#2]
add multiple array questions in a folder.

**Comment by Yukino2002** [comment]
I would like to take this issue up.

**Comment by realsahilsaini** [comment]
Hey @saujibua, can work on this ?

**Comment by destroyer5067** [comment]
Hey @saujibua can I take this issue?

**Comment by Aditya-wani02** [comment]
I like to work on it ...
I will provide multiple questions and their solution to help other .
plz assign it to me.

**Comment by saujibua** [comment]
sure you all guys can go ahead.

**Comment by Aditya-wani02** [comment]
Done By Me.. Pull Request given.Thank you for opportunity.

**Comment by ayushigeorge** [comment]
Can I add array questions in C?
