### ISSUE TITLE
Create a folder and add String problems and solutions.

### ISSUE THREAD

**Issue by saujibua** [saujibua/Data-Structures-and-Algorithms#3]
create a folder and add string problems and their solutions. Make it clean and precise.

**Comment by Yukino2002** [comment]
I would like to take this issue up.

**Comment by saujibua** [comment]
sure go ahead.

**Comment by destroyer5067** [comment]
Assign this issue to me, I am experienced in DSA and Competitive Programming

**Comment by saujibua** [comment]
you both can go ahead

**Comment by 55ritesh** [comment]
I would like to take this issue up.

**Comment by Ishantgarg-web** [comment]
Can you assign this issue to me

**Comment by saujibua** [comment]
But this issue has been resolved. Please check other issues to contribute
